const projectList = [
    {
        intId: 1,
        intParentId: null,
        chName: "تست1",
        chCreateDate: "1399/01/01",
        chExpireDate: "1399/01/15",
        intSupevisiorId: 1001,
        chSupevisiorName: "اقای ایکس",
        chProgress: 50,
        intProjectStateId: 1,
        chProjectStateName: "Doing",
        chDescribtion: "توضیحات تست 1",
        chComments: [],
        chFiles: [],
    },
    {
        intId: 2,
        intParentId: null,
        chName: "تست 2",
        chCreateDate: "1399/01/15",
        chExpireDate: "1399/01/30",
        intSupevisiorId: 1002,
        chSupevisiorName: "اقای ایکس 2",
        chProgress: 70,
        intProjectStateId: 1,
        chProjectStateName: "Doing",
        chDescribtion: "توضیحات تست 2",
        chComments: [],
        chFiles: [],
    },
    {
        intId: 3,
        intParentId: null,
        chName: "تست 3",
        chCreateDate: "1399/01/07",
        chExpireDate: "1399/01/20",
        intSupevisiorId: 1003,
        chSupevisiorName: "اقای ایکس 3",
        chProgress: 0,
        intProjectStateId: 0,
        chProjectStateName: "ToDo",
        chDescribtion: "توضیحات تست 3",
        chComments: [],
        chFiles: [],
    },
    {
        intId: 4,
        intParentId: null,
        chName: "تست 4",
        chCreateDate: "1399/01/07",
        chExpireDate: "1399/01/20",
        intSupevisiorId: 1001,
        chSupevisiorName: "اقای ایکس 1",
        chProgress: 10,
        intProjectStateId: 0,
        chProjectStateName: "ToDo",
        chDescribtion: "توضیحات تست 4",
        chComments: [],
        chFiles: [],
    },
    {
        intId: 5,
        intParentId: null,
        chName: "تست 5",
        chCreateDate: "1399/01/07",
        chExpireDate: "1399/01/20",
        intSupevisiorId: 1002,
        chSupevisiorName: "اقای ایکس 2",
        chProgress: 90,
        intProjectStateId: 0,
        chProjectStateName: "ToDo",
        chDescribtion: "توضیحات تست 5",
        chComments: [],
        chFiles: [],
    },
];

module.exports = projectList;